apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://172.17.0.1:8042
    jsonData:
      version: Flux
      organization: company1
      defaultBucket: gateway1
      tlsSkipVerify: true
    secureJsonData:
      token: randomTokenValue
